/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache static app shell assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// 1. Web Push Event Listener (Enhanced for Strong Vibration & Audio Popups)
self.addEventListener('push', (event: PushEvent) => {
  let title = 'Task Reminder 🌸';
  let body = 'You have an upcoming task due soon.';
  let url = '/tasks';

  if (event.data) {
    try {
      const data = event.data.json();
      if (data.title) title = data.title;
      if (data.body) body = data.body;
      if (data.url) url = data.url;
    } catch (e) {
      try {
        const textData = event.data.text();
        if (textData) body = textData;
      } catch (err) {}
    }
  }

  // Strong multi-pulse vibration pattern: 500ms vibrate, 150ms pause, 500ms vibrate, 150ms pause, 800ms alarm burst
  const options = {
    body: body,
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [500, 150, 500, 150, 500, 150, 800],
    silent: false,
    priority: 'high',
    urgency: 'high',
    timestamp: Date.now(),
    tag: 'task-reminder-' + Date.now(),
    renotify: true,
    requireInteraction: true,
    actions: [
      { action: 'open', title: '👁️ View Task' },
      { action: 'dismiss', title: '✖️ Dismiss' },
    ],
    data: {
      url: url,
    },
  } as any;

  event.waitUntil(self.registration.showNotification(title, options));
});

// 2. Notification Click Handler (Focus existing window or open PWA and navigate)
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  if (event.action === 'dismiss') {
    return;
  }

  const targetUrl = event.notification.data?.url || '/tasks';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.focus();
            if ('navigate' in client && targetUrl) {
              (client as WindowClient).navigate(targetUrl);
            }
            return;
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(targetUrl);
        }
      })
  );
});
