/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache static app shell assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// 1. Web Push Event Listener optimized for Mobile (Android & iOS PWA)
self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'Task Reminder 🌸';
    const options = {
      body: data.body || 'You have an upcoming task due soon.',
      icon: data.icon || '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      vibrate: [200, 100, 200, 100, 200],
      tag: 'task-reminder-' + (data.taskOccurrenceId || Date.now()),
      renotify: true,
      requireInteraction: true,
      data: {
        url: data.url || '/tasks',
        taskOccurrenceId: data.taskOccurrenceId,
      },
    } as any;

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (err) {
    console.error('Error handling web push event:', err);
  }
});

// 2. Notification Click Handler (Focus existing window or open PWA and navigate)
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/tasks';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // If PWA window is already open, focus it
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.focus();
            if ('navigate' in client && targetUrl) {
              (client as WindowClient).navigate(targetUrl);
            }
            return;
          }
        }
        // If PWA is closed, open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(targetUrl);
        }
      })
  );
});
