/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache static app shell assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// 1. Web Push Event Listener (Guaranteed banner display for all Push events)
self.addEventListener('push', (event: PushEvent) => {
  let title = 'Task Reminder 🌸';
  let body = 'You have an upcoming task due soon.';
  let url = '/tasks';

  if (event.data) {
    try {
      const data = event.data.json();
      if (data.title) title = data.title;
      if (data.body) body = data.body;
      if (data.url) url = data.url;
    } catch (e) {
      try {
        const textData = event.data.text();
        if (textData) body = textData;
      } catch (err) {}
    }
  }

  const options = {
    body: body,
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [200, 100, 200, 100, 200],
    tag: 'task-reminder-' + Date.now(),
    renotify: true,
    requireInteraction: true,
    data: {
      url: url,
    },
  } as any;

  event.waitUntil(self.registration.showNotification(title, options));
});

// 2. Notification Click Handler (Focus existing window or open PWA and navigate)
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/tasks';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.focus();
            if ('navigate' in client && targetUrl) {
              (client as WindowClient).navigate(targetUrl);
            }
            return;
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(targetUrl);
        }
      })
  );
});
